branches: [ master, codeberg-test ]

pipeline:
  build:
    image: ubuntu:latest
    pull: true
    commands: |
      echo 'deb https://fr.archive.ubuntu.com/ jammy main' >> /etc/apt/sources.list
      apt-get update && apt-get install -y openjdk-17-jdk libicu-dev libcurl4-openssl-dev libjansson-dev libgmp-dev
      ./gradlew gui:build
      ./gradlew text-client:build
      ./gradlew client-java:build
      ./scripts/buildsite.sh
      ./gradlew allTests
