branches: [ master, codeberg-test ]

pipeline:
  build:
    image: ubuntu
    commands: |
      apt-get update && apt-get install -y openjdk-17-jdk libicu-dev libcurl4-openssl-dev libjansson-dev
      ./gradlew build
  run-tests:
    commands:
      ./gradlew allTests
      ./gradlew gui:test
