branches: [ master, codeberg-test ]

pipeline:
  build:
    image: debian
    pull: true
    commands: |
      apt-get update && apt-get install -y openjdk-17-jdk libicu-dev libcurl4-openssl-dev libjansson-dev libgmp-dev libedit-dev
      ./gradlew gui:build
      ./gradlew text-client:build
      ./gradlew client-java:build
      ./scripts/buildsite.sh
      ./gradlew allTests
